### ISSUE TITLE
Add to Bower

### ISSUE THREAD

**Issue by migig** [jlong/css-spinners#11]
Pretty please!

So we can integrate into our build system.

**Comment by thecotne** [comment]
@migig it's already added
`bower install css-spinners`

**Comment by jlong** [comment]
Yep it's already on bower!

**Comment by migig** [comment]
Yes but the docs didn't say so, so I didn't know!

I see they've been updated now, excellent.

**Comment by thecotne** [comment]
@migig actually any github repo can be downloaded with bower
like this `bower install <github-username>/<repo-name>`
so if you want `css-spinners` by `jlong`
you can install with `bower install jlong/css-spinners`

**Comment by migig** [comment]
@thecotne :smiley:
