### ISSUE TITLE
What browser versions are supported?

### ISSUE THREAD

**Issue by KelseyDH** [jlong/css-spinners#14]
I couldn't find information in the documentation here or on the css-spinners website about what browser versions are supported.  E.g. can Internet Explorer 8 handle them?

**Comment by jlong** [comment]
If you use the following markup:

    <div class="loader-class-name">
        Loading...
    </div>

The text "Loading..." will be displayed on browsers like IE 8, that don't support CSS animation.

**Comment by KelseyDH** [comment]
Thanks, I tested this on IE 9 and can also confirm it shows the "Loading..." text correctly instead of the CSS animation as well.
