### ISSUE TITLE
Website is a 404 

### ISSUE THREAD

**Issue by jfeldstein** [jlong/css-spinners#26]
At the time I'm writing this, the link to www. css-spinners.com as found in the readme is 404'ing. Showing a google apps broken-robot image.

**Comment by MoOx** [comment]
Having this issue as well.

**Comment by jlong** [comment]
Yes. Unfortunately DivShot shutdown a while back and took the site offline. I am working to get it back online but it will be a while yet.

**Comment by Iulius90** [comment]
I wanted to see the spinners in action, without installing anything and since the website is down I created a codepen: http://codepen.io/Iulius90/pen/RaeWmY
Thought this could be useful.

**Comment by jlong** [comment]
Thanks!

**Comment by wesleywerner** [comment]
I will suggest updating the website link to the codepen url above.
These are great by the way!

**Comment by shubhendrapatel** [comment]
we can also use **GitHub Pages** for hosting website.

**Comment by Ne-Ne** [comment]
> we can also use GitHub Pages for hosting website.

This would make more sense..

Create a gh-branch then update the domain records.

**Comment by jlong** [comment]
@Ne-Ne or @shubhendrapatel If I made one of you a team member can you take care of creating the branch? I can update the domain records. Sorry, my time is limited atm.

**Comment by shubhendrapatel** [comment]
yeah sure

**Comment by jlong** [comment]
@shubhendrapatel I've made you a collaborator.

**Comment by shubhendrapatel** [comment]
instead of creating new branch we can also rename example.html -> index.html and set gh-pages to master branch.

**Comment by shubhendrapatel** [comment]
@jlong i have renamed example.tml => index.html,
updating **gh-pages** to **master** branch should work.

**Comment by jlong** [comment]
www.css-spinners.com is back up. Thanks!
