### ISSUE TITLE
Any plans to support Bourbon?

### ISSUE THREAD

**Issue by xmlking** [jlong/css-spinners#4]
I am using Bourbon in my project and thinking it might be too heavy to use compass.
wonder if you have any plans to support Bourbon in place of Compass

**Comment by jlong** [comment]
I'd love to have support for Bourbon! One way of doing this would be to remove the dependency on Compass entirely. We are only using a few of the CSS3 mixins. It might be possible to write these ourselves or to require something like auto-prefixer.

**Comment by jlong** [comment]
Anyone want to work on this?

**Comment by jlong** [comment]
Closing this for now.
